---
title: "The Impact of Early Life Stress on Susceptibility and Severity of Symptoms of Coronavirus"
author: Andrew Dismukes
date: "`r Sys.Date()`"
output: 
 html_document:
   toc: true
   toc_float: true
   toc_depth: 2
---
## OVERVIEW {.tabset}
### WRITING TEAM LEADER CONTACT INFORMATION 
   - Writing Team Lead: Andrew Dismukes
   - Institution: Penn State
   - Address: 430 Moore Building, University Park, PA, 16801
   - Telephone: NA at present (working from home)
   - Email: aud958@PSU.edu (preferred)
  - WTL Is affiliated with ECHO, but not an ECHO PI
  - Will not include data from Navajo Birth Cohort
  
 <!---Link: https://andrewdismukes.github.io/Papers_ECHO_2020_COVID/Proposal_Overview.html)-->
  
### WRITING TEAM MEMBERS 

Initial List:

Fichorova, Raina Nakova,M.D. <rfichorova@bwh.harvard.edu>,   
rjschmidt@ucdavis.edu,   
Racicoka@msu.edu,   
breton@usc.edu,   
bastain@usc.edu,   
Frank D. Gilliland" <Gillilan@usc.edu>,   
Zhanghuc@usc.edu,   
jec373@drexel.edu   
Jodi Ganiban <ganiban@gwu.edu>,   
Jenae Neiderhiser <jenaemn@gmail.com>,   
Leslie Leve <leve@uoregon.edu>,   
Rashelle Musci <rmusci1@jhu.edu>  

### DAC UTILIZATION 

- Proposal WILL use DAC
- Rashelle Musci is primary Analyst

### CONFLICT OF INTEREST, FUNDING, IRB 

- COI completed by WTL
- IRB approval for proposal not applied for
- This collaboration will not involve an institution or company that is not located in the United States
- Will be submitted to peer reviewed journal


## PROPOSAL {.tabset}
### TYPE OF PROPOSAL
 - Multiple Cohort awardees and DAC involved
 - Neurodevelopment focus, but inclusive of parents 
 - requires individual level data
 - all data as described in this proposal (including primary exposures, outcomes, confounders, and modifiers) are listed in the protocol
 - no biospecimens, proprietary measures, genetics, or assay data required
### DATA


## STUDY DESIGN {.tabset}

### Lay Language Abstract 

The present proposal seeks to examine the relationship between indicators of early life stressors and the development of COVID 19 stress, symptom severity, and potentially latent profiles of symptoms. If a relationship between early life stress and these outcomes exist, potential moderation by near termstress will be examined. 

### Background

The impact of Early Life Adversity (ELA) on susceptibility for infectious disease has been well characterized for a number of prevalent infectious diseases, including HSV, the common cold, Epstein-Barr and cytomegalovirus, as well as common ailments including cardiovascular disease, diabetes, respiratory illness and arthritis. A common explanation for this association involves the interaction between the developing stress response system and immune system, such that these systems adapt and calibrate to stress exposure to provide near-term resiliency to stress, potentially with a trade-off of  predisposing to long term risk including decreased immune function and susceptibility to infectious disease. Therefore, it is likely that exposure to Early Life Adversity will manifest in meaningful differences in risk for Coronavirus. Knowing whether this is the case is critical for targeted intervention and disease containment as well as allocation of resources in response to COVID 19. 

### Specific Aims and Hypotheses 

- Hypothesis 1 : History of Early Life Adversity will predispose to stress associated with COVID 19, and influence the severity of COVID 19 related stressors, moderated by near term stressors. 

- Hypothesis 2: History of Early Life Adversity will predispose to occurence of, severity of, and differential profiles of symptoms associated with COVID 19, moderated by near term stressors.


### Overlap with existing ECHO publications or proposals 
 - There are no known overlaps with *approved* ECHO analysis proposals. 
 - There is potential overlap/complementarity with the Ganiban led proposal "Residential resources and COVID-19 hardships within communities of color and lower income communities" and the Margolis led proposal "Chemical and Social Exposures Contribute To COVID-19-Related Acute Stress Symptoms in Children" however the WTL of this project is on the writing team for the Ganiban led proposal and Dr. Margolis has been suggested as a reviewer for the present proposal. The point of overlap is the development of a latent profile of near term stressors with the latter proposal. The present writing team would be interested in moving forward collaboratively with these other interesting and highly relevant proposals and working otgether too ensure that we answer unique questions but share resources and ideas where possible.   
 
 
## MEASUREMENTS {.tabset}
### Exposures  
#### Long Term Stressors  
#### Parent:  
  - ACES (Parent report on self)  
  - Childhood Trauma Questionnaire 
  - Life Stressor checklist - R  
  
#### Child:  
  - ACES (Child report on self)  
  - ACES (Parent report on Child)  
  - Perceived Stress Scale
  - Promis psychological stress (child self report and parent proxy)

### Outcomes  
#### Parent:    
 - COVID 19 questionnaire Parts A & B parent report on self  
 
#### Child:    

 - COVID 19 questionnaire Parts A & B child report on self
 - COVID 19 questionnaire Parts A & B parent report on child

### Confounders and modifiers 

- BMI
- SES
- Education
- Age
- Sex
- Race/Ethnicity

### Moderators

#### Near Term Stresors:  
#### Parent:  
#### Child: 